name: color-wars-site

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '[PASSWORD HERE]'
      TZ: America/New_York
    volumes:
      - database:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  httpd:
    build:
      context: ./
    depends_on:
      - mariadb
    environment:
      DB_HOSTNAME: 'mariadb'
      DB_PASSWORD: '[PASSWORD HERE]'
#    volumes:
#      - ./ssl.conf:/etc/apache2/conf-enabled/ssl.conf
#      - ./privkey.pem:/etc/apache2/conf/privkey.pem
#      - ./fullchain.pem:/etc/apache2/conf/fullchain.pem
    ports:
      - "80:80"
#      - "443:443"

volumes:
  database: