name: color-wars-site

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      TZ: America/New_York
    env_file:
      - ./passwords.env
    volumes:
      - database:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  httpd:
    build:
      context: ./
    depends_on:
      - mariadb
    environment:
      DB_HOSTNAME: 'mariadb'
      # DB_PASSWORD variable must be set in a file called passwords.env
      ADMIN_USERNAME: admin
      # ADMIN_PASSWORD variable must be set in a file called passwords.env
      AUTO_APPROVE_FIRST_USER: true
    env_file:
      - ./passwords.env
    volumes:
      - ./api:/var/www/api
      - ./public:/var/www/html
    ports:
      - "3000:80"

volumes:
  database: